language: go
go:
  - master
install:
  - export GOPATH=$HOME/gopath
  - export CGO_CPPFLAGS="-I$GOPATH/src/github.com/harmony-one/bls/include -I$GOPATH/src/github.com/harmony-one/mcl/include"
  - export CGO_LDFLAGS="-L$GOPATH/src/github.com/harmony-one/bls/lib -L$GOPATH/src/github.com/harmony-one/mcl/lib"
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GOPATH/src/github.com/harmony-one/bls/lib
  - cd $HOME/gopath/src
  - cd github.com/harmony-one
  - git clone https://github.com/harmony-one/mcl.git
  - cd mcl
  - make test
  - cd ../harmony
  - go get -t -v ./...
  - go get -u golang.org/x/lint/golint
  - go get gopkg.in/check.v1
  - ./scripts/travis_checker.sh
  - go build -v ./...
script:
  - ./scripts/travis_checker.sh
notifications:
  slack: harmonyone:gggCd1QQopsQAW8JYgBWiH7M
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
