language: go

go:
  - master
install: |
  export GOPATH=$HOME/gopath
  mkdir -p $HOME/gopath/src/harmony-benchmark
  rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/harmony-benchmark/
  export TRAVIS_BUILD_DIR=$HOME/gopath/src/harmony-benchmark
  cd $HOME/gopath/src/harmony-benchmark