version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
hooks:
  BeforeInstall:
    - location: aws-scripts/say_hello.sh
      timeout: 10
      runas: root
  AfterInstall:
    - location: aws-scripts/setup_golang.sh #setup golang
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws-scripts/say_hello.sh  #maybe start the server.
      timeout: 10
      runas: root
  ApplicationStop:
    - location: aws-scripts/say_hello.sh
      timeout: 10
      runas: root