version: "2.2"

services:
  test:
    container_name: posichain-test
    build:
      dockerfile: Dockerfile.test
      context: .
    volumes:
      - .:/root/go/src/github.com/PositionExchange/posichain

  workspace:
    container_name: posichain-workspace
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/root/go/src/github.com/PositionExchange/posichain
    tty: true
