version: "2.1"

services:
  dnsserver:
    container_name: posichain-dnsserver
    build:
      dockerfile: Dockerfile.dnsserver
      context: .
    volumes:
      - ./dns/zones:/etc/bind/zones
    networks:
      blockchain:
        ipv4_address: 172.189.0.3

  bootnode1:
    container_name: posichain-bootnode1
    image: posichain-bootnode
    build:
      dockerfile: Dockerfile.bootnode
      context: .
    environment:
      NODE_IP: 172.189.0.8
      NODE_PORT: 9876
    depends_on:
      - dnsserver
    dns: 172.189.0.3
    networks:
      blockchain:
        ipv4_address: 172.189.0.8

  node1:
    container_name: posichain-node1
    image: posichain-peernode
    build:
      dockerfile: Dockerfile.node
      context: .
    depends_on:
      - dnsserver
      - bootnode1
    volumes:
      - node1-data:/app/data
      - ./runtime/node1/blskeys:/app/blskeys
      - ./runtime/node1/passphrases:/app/passphrases
      - ./runtime/node1/harmony.conf:/app/harmony.conf
    ports:
      - "40000:40000"
    security_opt:
      - "apparmor=unconfined"
    cap_add:
      - SYS_PTRACE
    dns: 172.189.0.3
    networks:
      blockchain:
        ipv4_address: 172.189.0.9

  node2:
    container_name: posichain-node2
    image: posichain-peernode
    depends_on:
      - dnsserver
      - bootnode1
      - node1
    volumes:
      - node2-data:/app/data
      - ./runtime/node2/blskeys:/app/blskeys
      - ./runtime/node2/passphrases:/app/passphrases
      - ./runtime/node2/harmony.conf:/app/harmony.conf
    dns: 172.189.0.3
    networks:
      blockchain:
        ipv4_address: 172.189.0.10

  node3:
    container_name: posichain-node3
    image: posichain-peernode
    depends_on:
      - dnsserver
      - bootnode1
      - node1
    volumes:
      - node3-data:/app/data
      - ./runtime/node3/blskeys:/app/blskeys
      - ./runtime/node3/passphrases:/app/passphrases
      - ./runtime/node3/harmony.conf:/app/harmony.conf
    ports:
      - "35000:5000"# Explorer service
      - "39700:9700"
    dns: 172.189.0.3
    networks:
      blockchain:
        ipv4_address: 172.189.0.11

volumes:
  node1-data:
    driver: local
  node2-data:
    driver: local
  node3-data:
    driver: local

networks:
  blockchain:
    ipam:
      config:
        - subnet: 172.189.0.0/24