services:
  test_all:
    container_name: posichain-test
    build:
      dockerfile: Dockerfile.test
      context: .
    command:
      - bash
      - -c
      - "make go-get && make && ./scripts/travis_go_checker.sh"
