version: "2.1"

services:
  dnsserver:
    container_name: posichain-dnsserver
    build:
      dockerfile: Dockerfile.dnsserver
      context: .
    volumes:
      - ./dns/zones:/etc/bind/zones
    networks:
      blockchain:
        ipv4_address: 172.189.0.3

  bootnode1:
    container_name: posichain-bootnode1
    build:
      dockerfile: Dockerfile.bootnode
      context: .
      args:
        BUILD_NODE_DIR: /workspace/harmony/runtime/bootnode1
        BUILD_NODE_IP: 172.189.0.8
        BUILD_NODE_PORT: 9876
    depends_on:
      - dnsserver
    dns: 172.189.0.3
    networks:
      blockchain:
        ipv4_address: 172.189.0.8
  node1:
    container_name: posichain-node1
    build:
      dockerfile: Dockerfile.node
      context: .
      args:
        BUILD_NODE_DIR: /workspace/harmony/runtime/node1
        BUILD_BLS_PASSPHRASE_FILENAME: passphrase1.txt
    depends_on:
      - dnsserver
      - bootnode1
    volumes:
      - /workspace/harmony/runtime/node1/bin
      - /workspace/harmony/runtime/node1/blskeys
      - /workspace/harmony/runtime/node1/data
      - /workspace/harmony/runtime/node1/logs
      - ./runtime/node1:/workspace/harmony/runtime/node1
    dns: 172.189.0.3
    networks:
      blockchain:
        ipv4_address: 172.189.0.9
  node2:
    container_name: posichain-node2
    build:
      dockerfile: Dockerfile.node
      context: .
      args:
        BUILD_NODE_DIR: /workspace/harmony/runtime/node2
        BUILD_BLS_PASSPHRASE_FILENAME: passphrase1.txt
    depends_on:
      - dnsserver
      - bootnode1
    volumes:
      - /workspace/harmony/runtime/node2/bin
      - /workspace/harmony/runtime/node2/blskeys
      - /workspace/harmony/runtime/node2/data
      - /workspace/harmony/runtime/node2/logs
      - ./runtime/node2:/workspace/harmony/runtime/node2
    dns: 172.189.0.3
    networks:
      blockchain:
        ipv4_address: 172.189.0.10
  node3:
    container_name: posichain-node3
    build:
      dockerfile: Dockerfile.node
      context: .
      args:
        BUILD_NODE_DIR: /workspace/harmony/runtime/node3
        BUILD_BLS_PASSPHRASE_FILENAME: passphrase1.txt
    depends_on:
      - dnsserver
      - bootnode1
    volumes:
      - /workspace/harmony/runtime/node3/bin
      - /workspace/harmony/runtime/node3/blskeys
      - /workspace/harmony/runtime/node3/data
      - /workspace/harmony/runtime/node3/logs
      - ./runtime/node3:/workspace/harmony/runtime/node3
    ports:
      - "35000:5000"# Explorer service
    dns: 172.189.0.3
    networks:
      blockchain:
        ipv4_address: 172.189.0.11
networks:
  blockchain:
    ipam:
      config:
        - subnet: 172.189.0.0/24