version: 2.1

jobs:
  build:
    machine: true
    resource_class: xlarge
    working_directory: ~/repo
    steps:
      - run:
          name: Install Linux Dependencies
          command: |
            sudo apt update -y && sudo apt install -y libgmp-dev libssl-dev jq make gcc g++
      - run:
          name: Install Golang
          command: |
            cd /tmp
            wget https://go.dev/dl/go1.18.4.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go && tar -C /usr/local -xzf go1.18.4.linux-amd64.tar.gz
            export GOPATH=/home/circleci/.go_workspace
            export PATH=$PATH:$GOPATH/bin
            go version
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Go Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Install Building Tools
          command: |
            git clone https://github.com/PositionExchange/mcl.git ~/mcl
            git clone https://github.com/PositionExchange/bls.git ~/bls
            (cd ~/mcl; make -j4)
            (cd ~/bls; make BLS_SWAP_G=1 -j4)
            go install golang.org/x/tools/cmd/goimports@latest
            go install github.com/fjl/gencodec@latest
            go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
            go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1
            ./scripts/install_build_tools.sh
            make go-get
      - run:
          name: Run tests
          command: |
            make
            bash ./scripts/travis_go_checker.sh

workflows:
  build_and_test:
    jobs:
      - build
