version: "2.1"

services:
  dnsserver:
    container_name: posichain-dnsserver
    build:
      dockerfile: .local/Dockerfile.dnsserver
      context: ..
    volumes:
      - ./dns/zones:/etc/bind/zones
    networks:
      blockchain:
        ipv4_address: 172.189.0.3

  bootnode1:
    container_name: posichain-bootnode1
    image: posichain-bootnode
    build:
      dockerfile: .local/Dockerfile.bootnode
      context: ..
    environment:
      NODE_IP: 172.189.0.8
      NODE_PORT: 9876
    depends_on:
      - dnsserver
    ports:
      - "24001:40000"
    dns: 172.189.0.3
    networks:
      blockchain:
        ipv4_address: 172.189.0.8

  # Shard 2 (random)
  node1:
    container_name: posichain-node1
    image: posichain-peernode
    build:
      dockerfile: .local/Dockerfile.node
      context: ..
    depends_on:
      - dnsserver
      - bootnode1
    volumes:
      - node1-data:/app/data
      - node1-account:/root/.hmy_cli/account-keys
      - ./nodes/node1/blskeys:/app/blskeys
      - ./nodes/node1/passphrases:/app/passphrases
      - ./nodes/node1/harmony.conf:/app/harmony.conf
    environment:
      ENABLE_REMOTE_DEBUG: "false"
    ports:
      - "14000:40000"
      - "19500:9500" # Http RPC public
      - "19501:9501" # Http RPC auth
      - "19800:9800"# WS RPC public
      - "19801:9801"# WS RPC auth
      - "15000:5000"
    security_opt:
      - "apparmor=unconfined"
    cap_add:
      - SYS_PTRACE
    dns: 172.189.0.3
    networks:
      blockchain:
        ipv4_address: 172.189.0.9

  # Shard 3 (random)
  node2:
    container_name: posichain-node2
    image: posichain-peernode
    depends_on:
      - dnsserver
      - bootnode1
      - node1
    volumes:
      - node2-data:/app/data
      - node2-account:/root/.hmy_cli/account-keys
      - ./nodes/node2/blskeys:/app/blskeys
      - ./nodes/node2/passphrases:/app/passphrases
      - ./nodes/node2/harmony.conf:/app/harmony.conf
    ports:
      - "24000:40000"
      - "29500:9500"# Http RPC public
      - "29501:9501"# Http RPC auth
      - "29800:9800"# WS RPC public
      - "29801:9801"# WS RPC auth
    security_opt:
      - "apparmor=unconfined"
    cap_add:
      - SYS_PTRACE
    dns: 172.189.0.3
    networks:
      blockchain:
        ipv4_address: 172.189.0.10

  # Shard 0 (random)
  node3:
    container_name: posichain-node3
    image: posichain-peernode
    depends_on:
      - dnsserver
      - bootnode1
      - node1
    volumes:
      - node3-data:/app/data
      - node3-account:/root/.hmy_cli/account-keys
      - ./nodes/node3/blskeys:/app/blskeys
      - ./nodes/node3/passphrases:/app/passphrases
      - ./nodes/node3/harmony.conf:/app/harmony.conf
    environment:
      ENABLE_REMOTE_DEBUG: "true"
    ports:
      - "34000:40000"
      - "39500:9500"# Http RPC public
      - "39501:9501"# Http RPC auth
      - "39800:9800"# WS RPC public
      - "39801:9801"# WS RPC auth
    security_opt:
      - "apparmor=unconfined"
    cap_add:
      - SYS_PTRACE
    dns: 172.189.0.3
    networks:
      blockchain:
        ipv4_address: 172.189.0.11

  # Shard 1 (random)
  node4:
    container_name: posichain-node4
    image: posichain-peernode
    depends_on:
      - dnsserver
      - bootnode1
      - node1
    volumes:
      - node4-data:/app/data
      - node4-account:/root/.hmy_cli/account-keys
      - ./nodes/node4/blskeys:/app/blskeys
      - ./nodes/node4/passphrases:/app/passphrases
      - ./nodes/node4/harmony.conf:/app/harmony.conf
    ports:
      - "44000:40000"
      - "49500:9500"# Http RPC public
      - "49501:9501"# Http RPC auth
      - "49800:9800"# WS RPC public
      - "49801:9801"# WS RPC auth
    security_opt:
      - "apparmor=unconfined"
    cap_add:
      - SYS_PTRACE
    dns: 172.189.0.3
    networks:
      blockchain:
        ipv4_address: 172.189.0.12

  node5:
    container_name: posichain-node5
    image: posichain-peernode
    depends_on:
      - dnsserver
      - bootnode1
      - node1
    volumes:
      - node5-data:/app/data
      - node5-account:/root/.hmy_cli/account-keys
      - ./nodes/node5/blskeys:/app/blskeys
      - ./nodes/node5/passphrases:/app/passphrases
      - ./nodes/node5/harmony.conf:/app/harmony.conf
    ports:
      - "35000:5000"# Explorer service
      - "59500:9500"# Http RPC public
      - "59501:9501"# Http RPC auth
      - "59800:9800"# WS RPC public
      - "59801:9801"# WS RPC auth
      - "54000:40000"
    security_opt:
      - "apparmor=unconfined"
    cap_add:
      - SYS_PTRACE
    dns: 172.189.0.3
    networks:
      blockchain:
        ipv4_address: 172.189.0.13

volumes:
  node1-data:
    driver: local
  node1-account:
    driver: local
  node2-data:
    driver: local
  node2-account:
    driver: local
  node3-data:
    driver: local
  node3-account:
    driver: local
  node4-data:
    driver: local
  node4-account:
    driver: local
  node5-data:
    driver: local
  node5-account:
    driver: local

networks:
  blockchain:
    ipam:
      config:
        - subnet: 172.189.0.0/24